/*
SQLyog Community Edition- MySQL GUI v6.07
Host - 5.5.5-10.4.21-MariaDB : Database - login
*********************************************************************
Server version : 5.5.5-10.4.21-MariaDB
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

create database if not exists `login`;

USE `login`;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*Table structure for table `centro` */

DROP TABLE IF EXISTS `centro`;

CREATE TABLE `centro` (
  `centro_id` int(11) NOT NULL AUTO_INCREMENT,
  `centro_nombre` varchar(100) DEFAULT NULL,
  `centro_direccion` varchar(30) DEFAULT NULL,
  `centro_telefono` int(10) DEFAULT NULL,
  `centro_regional` int(11) DEFAULT NULL,
  PRIMARY KEY (`centro_id`),
  KEY `centro_regional` (`centro_regional`),
  CONSTRAINT `centro_ibfk_1` FOREIGN KEY (`centro_regional`) REFERENCES `regional` (`reg_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `centro` */

/*Table structure for table `centro_tiene_programa` */

DROP TABLE IF EXISTS `centro_tiene_programa`;

CREATE TABLE `centro_tiene_programa` (
  `centroprograma_id` int(11) NOT NULL AUTO_INCREMENT,
  `centro_id` int(11) DEFAULT NULL,
  `progra_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`centroprograma_id`),
  KEY `centro_id` (`centro_id`),
  KEY `progra_id` (`progra_id`),
  CONSTRAINT `centro_tiene_programa_ibfk_1` FOREIGN KEY (`centro_id`) REFERENCES `centro` (`centro_id`),
  CONSTRAINT `centro_tiene_programa_ibfk_2` FOREIGN KEY (`progra_id`) REFERENCES `programa` (`id_programa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `centro_tiene_programa` */

/*Table structure for table `competencia` */

DROP TABLE IF EXISTS `competencia`;

CREATE TABLE `competencia` (
  `comp_id` int(11) NOT NULL AUTO_INCREMENT,
  `comp_nombre` varchar(100) DEFAULT NULL,
  `comp_horas` int(11) DEFAULT NULL,
  `comp_programa` int(11) DEFAULT NULL,
  PRIMARY KEY (`comp_id`),
  KEY `comp_programa` (`comp_programa`),
  CONSTRAINT `competencia_ibfk_1` FOREIGN KEY (`comp_programa`) REFERENCES `programa` (`id_programa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `competencia` */

/*Table structure for table `fase` */

DROP TABLE IF EXISTS `fase`;

CREATE TABLE `fase` (
  `fase_id` int(11) NOT NULL AUTO_INCREMENT,
  `fase_nombre` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`fase_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `fase` */

/*Table structure for table `fichas` */

DROP TABLE IF EXISTS `fichas`;

CREATE TABLE `fichas` (
  `id_ficha` int(11) NOT NULL,
  `tipo_programa` enum('especializacion','tecnologo','tecnico') DEFAULT NULL,
  `nombre_programa` int(11) NOT NULL,
  `lider_ficha` int(11) NOT NULL,
  PRIMARY KEY (`id_ficha`),
  KEY `nombre_programa` (`nombre_programa`),
  KEY `lider_ficha` (`lider_ficha`),
  CONSTRAINT `fichas_ibfk_1` FOREIGN KEY (`nombre_programa`) REFERENCES `programa` (`id_programa`),
  CONSTRAINT `fichas_ibfk_2` FOREIGN KEY (`lider_ficha`) REFERENCES `usuarios` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `fichas` */

insert  into `fichas`(`id_ficha`,`tipo_programa`,`nombre_programa`,`lider_ficha`) values (12313,'tecnico',1,6),(245646,'especializacion',2,4),(1231313,'tecnologo',1,5),(2435346,'tecnologo',2,7);

/*Table structure for table `programa` */

DROP TABLE IF EXISTS `programa`;

CREATE TABLE `programa` (
  `id_programa` int(11) NOT NULL AUTO_INCREMENT,
  `pro_nombre` varchar(50) NOT NULL,
  PRIMARY KEY (`id_programa`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

/*Data for the table `programa` */

insert  into `programa`(`id_programa`,`pro_nombre`) values (1,'Adsi'),(2,'Ingles');

/*Table structure for table `regional` */

DROP TABLE IF EXISTS `regional`;

CREATE TABLE `regional` (
  `reg_id` int(11) NOT NULL AUTO_INCREMENT,
  `reg_nombre` varchar(100) DEFAULT NULL,
  `reg_direccion` varchar(30) DEFAULT NULL,
  `reg_telefono` int(10) DEFAULT NULL,
  `reg_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`reg_id`),
  KEY `reg_usuario` (`reg_usuario`),
  CONSTRAINT `regional_ibfk_1` FOREIGN KEY (`reg_usuario`) REFERENCES `usuarios` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `regional` */

/*Table structure for table `resultado_aprendizaje` */

DROP TABLE IF EXISTS `resultado_aprendizaje`;

CREATE TABLE `resultado_aprendizaje` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fase` varchar(20) DEFAULT NULL,
  `actividad` varchar(100) DEFAULT NULL,
  `competencia` varchar(200) DEFAULT NULL,
  `resultado` varchar(500) DEFAULT NULL,
  `tipo` enum('Clave','Transversal','Específico','Institucional') DEFAULT NULL,
  `fecha_inicio` date DEFAULT NULL,
  `fecha_fin` date DEFAULT NULL,
  `estado` enum('Evaluado','Pendiente','En ejecución') DEFAULT NULL,
  `observaciones` varchar(180) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=latin1;

/*Data for the table `resultado_aprendizaje` */

insert  into `resultado_aprendizaje`(`id`,`fase`,`actividad`,`competencia`,`resultado`,`tipo`,`fecha_inicio`,`fecha_fin`,`estado`,`observaciones`) values (1,'INDUCCIÃ“N','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÃ’N PROFESIONAL INTEGRAL Y P','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','ASUMIR LOS DEBERES Y DERECHOS CON BASE EN LAS LEYES Y LA NORMATIVA INSTITUCIONAL EN EL MARCO DE SU PROYECTO DE VIDA.','Institucional','0000-00-00','0000-00-00','Evaluado','JosÃ© Montesino'),(2,'INDUCCIÃ“N','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÃ’N PROFESIONAL INTEGRAL Y P','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','CONCERTAR ALTERNATIVAS Y ACCIONES DE FORMACIÃ“N PARA EL DESARROLLO DE LAS COMPETENCIAS DEL PROGRAMA FORMACIÃ“N, CON BASE EN LA POLÃTICA INSTITUCIONAL.','Institucional','0000-00-00','0000-00-00','Evaluado','JosÃ© Montesino'),(3,'INDUCCIÃ“N','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÃ’N PROFESIONAL INTEGRAL Y P','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','GESTIONAR LA INFORMACIÃ“N DE ACUERDO CON LOS PROCEDIMIENTOS ESTABLECIDOS Y CON LAS TECNOLOGÃAS DE LA INFORMACIÃ“N Y LA COMUNICACIÃ“N DISPONIBLES.','Institucional','0000-00-00','0000-00-00','Evaluado','JosÃ© Montesino'),(4,'INDUCCIÃ“N','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÃ’N PROFESIONAL INTEGRAL Y P','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','IDENTIFICAR LAS OPORTUNIDADES QUE EL SENA OFRECE EN EL MARCO DE LA FORMACIÃ“N PROFESIONAL DE ACUERDO CON EL CONTEXTO NACIONAL E INTERNACIONAL.','Institucional','0000-00-00','0000-00-00','Evaluado','JosÃ© Montesino'),(5,'INDUCCIÃ“N','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÃ’N PROFESIONAL INTEGRAL Y P','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','RECONOCER EL ROL DE LOS PARTICIPANTES EN EL PROCESO FORMATIVO, EL PAPEL DE LOS AMBIENTES DE APRENDIZAJE Y LA METODOLOGÃA DE FORMACIÃ“N, DE ACUERDO CON LA DINÃMICA ORGANIZACIONAL DEL SENA','Institucional','0000-00-00','0000-00-00','Evaluado','JosÃ© Montesino'),(6,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','INTERPRETAR EL INFORME DE REQUERIMIENTOS, PARA DETERMINAR LASNECESIDADES TECNOLÃ“GICAS EN EL MANEJO DE LA INFORMACIÃ“N, DE ACUERDOCON LAS NORMAS Y PROTOCOLOS ESTABLECIDOS EN LA EMPRESA','','0000-00-00','0000-00-00','Evaluado','Linley Moscote'),(7,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','VALORAR LA INCIDENCIA DE LOS DATOS EN LOS PROCESOS DEL MACROSISTEMA,TOMANDO COMO REFERENTE EL DICCIONARIO DE DATOS Y LASMINIESPECIFICACIONES, PARA LA CONSOLIDACIÃ“N DE LOS DATOS QUE INTERVIENEN,DE ACUERDO CON PARÃMETROS ESTABLECIDOS.','','0000-00-00','0000-00-00','','Julian Trespalacios'),(8,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','APLICAR BUENAS PRÃCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','IDENTIFICAR LAS CARACTERÃSTICAS DE LOS PROCESOS DE DESARROLLO DESOFTWARE, FRENTE AL REFERENTE DE CALIDAD ADOPTADO POR LA EMPRESA,AJUSTÃNDOLOS A LOS RESULTADOS DE LAS MEDICIONES, EVALUACIONES YRECOMENDACIONES REALIZADAS','','0000-00-00','0000-00-00','Evaluado','Maira Diaz'),(9,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','COMPRENDER TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y AUDITIVA','COMPRENDER FRASES Y VOCABULARIO HABITUAL SOBRE TEMAS DE INTERÃ‰S PERSONAL Y TEMAS TÃ‰CNICOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(10,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','COMPRENDER TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y AUDITIVA','COMPRENDER LA IDEA PRINCIPAL EN AVISOS Y MENSAJES BREVES, CLAROS Y SENCILLOS EN INGLÃ‰S TÃ‰CNICO','Clave','0000-00-00','0000-00-00','Pendiente',''),(11,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','ESPECIFICAR LOS REQUISITOS NECESARIOS PARA DESARROLLAR EL SISTEMA DE INFORMACION DE ACUERDO CON LAS NECESIDADES DEL CLIENTE.','APLICAR LAS TÃ‰CNICAS DE RECOLECCIÃ“N DE DATOS , DISEÃ‘ANDO LOSINSTRUMENTOS NECESARIOS PARA EL PROCESAMIENTO DE INFORMACIÃ“N, DEACUERDO CON LA SITUACIÃ“N PLANTEADA POR LA EMPRESA','','0000-00-00','0000-00-00','Evaluado','\"Linley Moscote\n'),(12,'(Los Aprendices no c','','','\r\n','','0000-00-00','0000-00-00','',''),(13,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','ESPECIFICAR LOS REQUISITOS NECESARIOS PARA DESARROLLAR EL SISTEMA DE INFORMACION DE ACUERDO CON LAS NECESIDADES DEL CLIENTE.','ELABORAR MAPAS DE PROCESOS QUE PERMITAN IDENTIFICAR LAS ÃREASINVOLUCRADAS EN UN SISTEMA DE INFORMACIÃ“N, UTILIZANDO HERRAMIENTASINFORMÃTICAS Y LAS TICâ€™S, PARA GENERAR INFORMES SEGÃšN LAS NECESIDADES DELA EMPRESA','','0000-00-00','0000-00-00','Evaluado','Karina Meza'),(14,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','INTERACTUAR EN LOS CONTEXTOS PRODUCTIVOS Y SOCIALES EN FUNCIÃ“N DE LOS PRINCIPIOS Y VALORES UNIVERSALES.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(15,'IDENTIFICACIÃ“N','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÃ“N.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','REDIMENSIONAR PERMANENTEMENTE SU PROYECTO DE VIDA DE ACUERDO CON LAS CIRCUNSTANCIAS DEL CONTEXTO Y CON VISIÃ“N PROSPECTIVA.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(16,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','CONSTRUIR EL MODELO CONCEPTUAL DEL MACROSISTEMA FRENTE A LOSREQUERIMIENTOS DEL CLIENTE, MEDIANTE EL USO E INTERPRETACIÃ“N DE LAINFORMACIÃ“N LEVANTADA, REPRESENTADO EN DIAGRAMAS DE CLASE, DEINTERACCIÃ“N, COLABORACIÃ“N Y CONTRATOS DE OPERACIÃ“N, DE ACUERDO CON LASDIFERENTES SECUENCIAS, FASES Y PROCEDIMIENTOS DEL SISTEMA.','','0000-00-00','0000-00-00','','Maira Diaz'),(17,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','ELABORAR EL INFORME DE LOS RESULTADOS DEL ANÃLISIS DEL SISTEMA DEINFORMACIÃ“N, DE ACUERDO CON LOS REQUERIMIENTOS DEL CLIENTE SEGÃšNNORMAS Y PROTOCOLOS ESTABLECIDOS.','','0000-00-00','0000-00-00','Evaluado','Maira Diaz'),(18,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','REPRESENTA EL BOSQUEJO DE LA SOLUCIÃ“N AL PROBLEMA PRESENTADO POR ELCLIENTE, MEDIANTE LA ELABORACIÃ“N DE DIAGRAMAS DE CASOS DE USO, APOYADOEN EL ANÃLISIS DEL INFORME DE REQUERIMIENTOS, AL CONFRONTAR LA SITUACIÃ“NPROBLEMICA CON EL USUARIO SEGÃšN NORMAS Y PROTOCOLOS DE LA ORGANIZACIÃ“N','','0000-00-00','0000-00-00','','Maira Diaz'),(19,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','COMPRENDER TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y AUDITIVA','LEER TEXTOS MUY BREVES Y SENCILLOS EN INGLÃ‰S GENERAL Y TÃ‰CNICO','Clave','0000-00-00','0000-00-00','Pendiente',''),(20,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','ESPECIFICAR LOS REQUISITOS NECESARIOS PARA DESARROLLAR EL SISTEMA DE INFORMACION DE ACUERDO CON LAS NECESIDADES DEL CLIENTE.','PLANTEAR DIFERENTES ALTERNATIVAS, DE MODELOS TECNOLÃ“GICOS DE INFORMACIÃ“NEMPRESARIAL, TENIENDO EN CUENTA LA PLATAFORMA TECNOLÃ“GICA DE LA EMPRESAY LAS TENDENCIAS DEL MERCADO, PARA DAR SOLUCIÃ“N A LAS SITUACIONESRELACIONADAS CON EL MANEJO DE LA INFORMACIÃ“N DE LA ORGANIZACIÃ“N.','','0000-00-00','0000-00-00','Pendiente','Jose Montesino'),(21,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','PARTICIPAR EN EL PROCESO DE NEGOCIACIÃ“N DE TECNOLOGÃA INFORMÃTICA PARA PERMITIR LA IMPLEMENTACIÃ“N DEL SISTEMA DE INFORMACIÃ“N.','INTERPRETAR EL DIAGNÃ“STICO DE NECESIDADES INFORMÃTICAS, PARA DETERMINARLAS TECNOLÃ“GICAS REQUERIDAS EN EL MANEJO DE LA INFORMACIÃ“N, DE ACUERDOCON LAS NORMAS Y PROTOCOLOS ESTABLECIDOS POR LA EMPRESA.','','0000-00-00','0000-00-00','','Linley Moscote'),(22,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','PRODUCIR TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y ORAL.','REPRODUCIR EN INGLÃ‰S FRASES O ENUNCIADOS SIMPLES QUE PERMITAN EXPRESAR DE FORMA LENTA IDEAS O CONCEPTOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(23,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','DESARROLLAR PERMANENTEMENTE LAS HABILIDADES PSICOMOTRICES Y DE PENSAMIENTO EN LA EJECUCIÃ“N DE LOS PROCESOS DE APRENDIZAJE.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(24,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','GENERAR HÃBITOS SALUDABLES EN SU ESTILO DE VIDA PARA GARANTIZAR LA PREVENCIÃ“N DE RIESGOS OCUPACIONALES DE ACUERDO CON EL DIAGNÃ“STICO DE SU CONDICIÃ“N FÃSICA INDIVIDUAL Y LA NATURALEZA Y COMPLEJIDAD DE SU DESEMPEÃ‘O LABORAL.','Transversal','0000-00-00','0000-00-00','','Maira MuÃ±oz'),(25,'ANÃLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÃ“N Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SIS','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','GENERAR PROCESOS AUTÃ“NOMOS Y DE TRABAJO COLABORATIVO PERMANENTES, FORTALECIENDO EL EQUILIBRIO DE LOS COMPONENTES RACIONALES Y EMOCIONALES ORIENTADOS HACIA EL DESARROLLO HUMANO INTEGRAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(26,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','APLICAR BUENAS PRÃCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','IDENTIFICAR LOS PUNTOS CRÃTICOS DE CONTROL EN LOS PROCESOS DE DESARROLLODE SOFTWARE, PARA ESTABLECER LAS ACCIONES A SEGUIR, GARANTIZANDO ELCUMPLIMIENTO DE LOS ESTÃNDARES DE CALIDAD, SIGUIENDO LOS LINEAMIENTOSESTABLECIDOS POR LA ORGANIZACIÃ“N','','0000-00-00','0000-00-00','Pendiente',''),(27,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','COMPRENDER TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y AUDITIVA','ENCONTRAR INFORMACIÃ“N ESPECÃFICA Y PREDECIBLE EN ESCRITOS SENCILLOS Y COTIDIANOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(28,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','COMPRENDER TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y AUDITIVA','ENCONTRAR VOCABULARIO Y EXPRESIONES DE INGLÃ‰S TÃ‰CNICO EN ANUNCIOS, FOLLETOS, PÃGINAS WEB, ETC','Clave','0000-00-00','0000-00-00','Pendiente',''),(29,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','DISEÃ‘AR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','CONSTRUIR EL PROTOTIPO DEL SISTEMA DE INFORMACIÃ“N, A PARTIR DEL ANÃLISIS DELAS CARACTERÃSTICAS FUNCIONALES DEL SISTEMA EN RELACIÃ“N CON FACILIDAD DEMANEJO, FUNCIONALIDAD Y EXPERIENCIA DEL USUARIO, APOYADO EN SOFTWAREAPLICADO SEGÃšN PROTOCOLOS DE DISEÃ‘O.','','0000-00-00','0000-00-00','Pendiente',''),(30,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','DISEÃ‘AR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','DISEÃ‘AR LA ARQUITECTURA DEL SOFTWARE, MEDIANTE LA INTERPRETACIÃ“N DE LASCLASES, OBJETOS Y MECANISMOS DE COLABORACIÃ“N, UTILIZANDO HERRAMIENTASTECNOLÃ“GICAS DE DISEÃ‘O, DE ACUERDO CON LAS TENDENCIAS DE LASTECNOLOGÃAS DE LA INFORMACIÃ“N Y LA COMUNICACIÃ“N.','','0000-00-00','0000-00-00','Pendiente',''),(31,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','DISEÃ‘AR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','DISEÃ‘AR LA ARQUITECTURA TECNOLÃ“GICA DEL SISTEMA DE INFORMACIÃ“N, MEDIANTEEL RECONOCIMIENTO DE HARDWARE Y SOFTWARE, DE ACUERDO CON LA TECNOLOGÃADISPONIBLE EN EL MERCADO, EL INFORME DE ANÃLISIS LEVANTADO Y EL DIAGRAMADE DISTRIBUCIÃ“N','','0000-00-00','0000-00-00','Pendiente',''),(32,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','DISEÃ‘AR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','DISEÃ‘AR LA ESTRUCTURA DE DATOS, A PARTIR DEL MODELO CONCEPTUALDETERMINADO EN EL ANÃLISIS DEL SISTEMA, UTILIZANDO HERRAMIENTASTECNOLÃ“GICAS DE BASES DE DATOS, SEGÃšN LAS NORMAS Y ESTÃNDARESESTABLECIDOS','','0000-00-00','0000-00-00','Pendiente',''),(33,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','DISEÃ‘AR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','ELABORAR EL INFORME DE DISEÃ‘O DEL SISTEMA DE INFORMACIÃ“N, DE ACUERDOCON LA SELECCIÃ“N DE LAS HERRAMIENTAS, TANTO DE SOFTWARE COMO DEHARDWARE, REQUERIDAS PARA LA SOLUCIÃ“N INFORMÃTICA.','','0000-00-00','0000-00-00','Pendiente',''),(34,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','PARTICIPAR EN EL PROCESO DE NEGOCIACIÃ“N DE TECNOLOGÃA INFORMÃTICA PARA PERMITIR LA IMPLEMENTACIÃ“N DEL SISTEMA DE INFORMACIÃ“N.','DEFINIR ESTRATEGIAS PARA LA ELABORACIÃ“N DE TÃ‰RMINOS DE REFERENCIA YPROCESOS DE EVALUACIÃ“N DE PROVEEDORES, EN LA ADQUISICIÃ“N DE TECNOLOGÃA,SEGÃšN PROTOCOLOS ESTABLECIDOS.','','0000-00-00','0000-00-00','Pendiente',''),(35,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','PARTICIPAR EN EL PROCESO DE NEGOCIACIÃ“N DE TECNOLOGÃA INFORMÃTICA PARA PERMITIR LA IMPLEMENTACIÃ“N DEL SISTEMA DE INFORMACIÃ“N.','PARTICIPAR EN LOS PERFECCIONAMIENTOS DE CONTRATOS INFORMÃTICOS,ESTABLECIENDO CLÃUSULAS TÃ‰CNICAS, QUE RESPONDAN A LAS NECESIDADES DELOS ACTORES DE LA NEGOCIACIÃ“N, DE ACUERDO CON LA LEY DE CONTRATACIÃ“N','','0000-00-00','0000-00-00','Pendiente',''),(36,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','PRODUCIR TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y ORAL.','COMPRENDER UNA AMPLIA VARIEDAD DE FRASES Y VOCABULARIO  EN INGLÃ‰S SOBRE TEMAS DE INTERÃ‰S PERSONAL Y TEMAS TÃ‰CNICOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(37,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','PRODUCIR TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y ORAL.','IDENTIFICAR FORMAS GRAMATICALES BÃSICAS EN TEXTOS Y DOCUMENTOS ELEMENTALES ESCRITOS EN INGLÃ‰S','Clave','0000-00-00','0000-00-00','Pendiente',''),(38,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','ASUMIR ACTITUDES CRÃTICAS , ARGUMENTATIVAS Y PROPOSITIVAS EN FUNCIÃ“N DE LA RESOLUCIÃ“N DE PROBLEMAS DE CARÃCTER PRODUCTIVO Y SOCIAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(39,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','ASUMIR RESPONSABLEMENTE LOS CRITERIOS DE PRESERVACIÃ“N Y CONSERVACIÃ“N DEL MEDIO AMBIENTE Y DE DESARROLLO SOSTENIBLE, EN EL EJERCICIO DE SU DESEMPEÃ‘O LABORAL Y SOCIAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(40,'DISEÃ‘O','DETERMINAR LA ESTRUCTURA LÃ“GICA DEL SISTEMA DE INFORMACIÃ“N','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','DESARROLLAR PROCESOS COMUNICATIVOS EFICACES Y ASERTIVOS DENTRO DE CRITERIOS DE RACIONALIDAD QUE POSIBILITEN LA CONVIVENCIA, EL ESTABLECIMIENTO DE ACUERDOS, LA CONSTRUCCIÃ“N COLECTIVA DEL CONOCIMIENTO Y LA RESOLUCIÃ“N DE PROBLEMAS DE CARÃCTER PRODUCTIVO Y SOCIAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(41,'DESARROLLO','CODIFICAR LOS MÃ“DULOS DEL SISTEMA DE INFORMACIÃ“N.','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÃ“N INFORMÃTICA.','CONSTRUIR EL PROGRAMA DE INSTALACIÃ“N DEL APLICATIVO, UTILIZANDO LASHERRAMIENTAS DE DESARROLLO DISPONIBLES EN EL MERCADO, SEGÃšN LASCARACTERÃSTICAS DE LA ARQUITECTURA DE LA SOLUCIÃ“N','','0000-00-00','0000-00-00','Pendiente',''),(42,'DESARROLLO','CODIFICAR LOS MÃ“DULOS DEL SISTEMA DE INFORMACIÃ“N.','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÃ“N INFORMÃTICA.','REALIZAR LA CODIFICACIÃ“N DE LOS MÃ“DULOS DEL SISTEMA Y EL PROGRAMAPRINCIPAL, A PARTIR DE LA UTILIZACIÃ“N DEL LENGUAJE DE PROGRAMACIÃ“NSELECCIONADO, DE ACUERDO CON LAS ESPECIFICACIONES DEL DISEÃ‘O','','0000-00-00','0000-00-00','Pendiente',''),(43,'DESARROLLO','CODIFICAR LOS MÃ“DULOS DEL SISTEMA DE INFORMACIÃ“N.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','APLICAR TÃ‰CNICAS DE CULTURA FÃSICA PARA EL MEJORAMIENTO DE SU EXPRESIÃ“N CORPORAL, DESEMPEÃ‘O LABORAL SEGÃšN LA NATURALEZA Y COMPLEJIDAD DEL ÃREA OCUPACIONAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(44,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','APLICAR BUENAS PRÃCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','APLICAR LOS ESTÃNDARES DE CALIDAD INVOLUCRADOS EN LOS PROCESOS DEDESARROLLO DE SOFTWARE, SIGUIENDO EL PLAN ESTABLECIDO PARA MANTENER LAINTEGRIDAD DE LOS PRODUCTOS DE TRABAJO DEFINIDOS, SEGÃšN LAS PRÃCTICASDE CONFIGURACIÃ“N ESTABLECIDAS POR LA EMPRESA','','0000-00-00','0000-00-00','Pendiente',''),(45,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','COMPRENDER TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y AUDITIVA','COMUNICARSE EN TAREAS SENCILLAS Y HABITUALES QUE REQUIEREN UN INTERCAMBIO SIMPLE Y DIRECTO DE INFORMACIÃ“N COTIDIANA Y TÃ‰CNICA','Clave','0000-00-00','0000-00-00','','Carlos Mendoza'),(46,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÃ“N INFORMÃTICA.','CONSTRUIR LA BASE DE DATOS, A PARTIR DEL MODELO DE DATOS DETERMINADO ENEL DISEÃ‘O DEL SISTEMA, UTILIZANDO SISTEMAS DE GESTIÃ“N DE BASE DE DATOS,SEGÃšN LOS PROTOCOLOS ESTABLECIDOS EN LA ORGANIZACIÃ“N','','0000-00-00','0000-00-00','Pendiente',''),(47,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÃ“N INFORMÃTICA.','CONSTRUIR LA INTERFAZ DE USUARIO, APOYADO EN LA EVALUACIÃ“N DEL PROTOTIPO,DETERMINANDO LAS ENTRADAS Y SALIDAS REQUERIDAS EN EL DISEÃ‘O Y DEFINIENDOLOS LINEAMIENTOS PARA LA NAVEGACIÃ“N, DE ACUERDO CON LAS NECESIDADES DELUSUARIO','','0000-00-00','0000-00-00','Pendiente',''),(48,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÃ“N INFORMÃTICA.','INTERPRETAR EL INFORME TÃ‰CNICO DE DISEÃ‘O, PARA DETERMINAR EL PLAN DETRABAJO DURANTE LA FASE DE CONSTRUCCIÃ“N DEL SOFTWARE, DE ACUERDO CON LASNORMAS Y PROTOCOLOS ESTABLECIDOS EN LA EMPRESA.','','0000-00-00','0000-00-00','Pendiente',''),(49,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','DISEÃ‘AR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','APLICAR POLÃTICAS Y MECANISMOS DE CONTROL EN EL DISEÃ‘O DEL SISTEMA DEINFORMACIÃ“N, MEDIANTE EL ANÃLISIS DE LA VULNERABILIDAD DE LA INFORMACIÃ“N,SIGUIENDO LOS PARÃMETROS ESTABLECIDOS POR LA ORGANIZACIÃ“N.','','0000-00-00','0000-00-00','Pendiente',''),(50,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','PRODUCIR TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y ORAL.','BUSCAR DE MANERA SISTEMÃTICA INFORMACIÃ“N ESPECÃFICA Y DETALLADA EN ESCRITOS EN INGLÃ‰S, MAS ESTRUCTURADOS Y CON MAYOR CONTENIDO TÃ‰CNICO','Clave','0000-00-00','0000-00-00','Pendiente',''),(51,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÃCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','APLICAR BUENAS PRÃCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','ELABORAR INSTRUMENTOS E INSTRUCTIVOS, REQUERIDOS POR EL ASEGURAMIENTODE LA CALIDAD, PARA DOCUMENTAR Y EVALUAR LOS PROCESOS DE DESARROLLO DESOFTWARE, DE ACUERDO CON LAS NORMAS Y PROCEDIMIENTOS ESTABLECIDASPOR LA EMPRESA','','0000-00-00','0000-00-00','Pendiente',''),(52,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÃCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','APLICAR BUENAS PRÃCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','EVALUAR PROCESOS Y PRODUCTOS DE DESARROLLO DE SOFTWARE, DOCUMENTAR YCONCERTAR ACCIONES A SEGUIR, PARA GARANTIZAR EL CUMPLIMIENTO DE LASNORMAS ESTABLECIDAS, DE ACUERDO CON EL PLAN DEFINIDO Y CON LOS CRITERIOSDE MEDICIÃ“N, MÃ‰TRICAS Y POLÃTICAS DETERMINADOS POR LA EMPRESA','','0000-00-00','0000-00-00','Pendiente',''),(53,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÃCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','COMPRENDER TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y AUDITIVA','REALIZAR INTERCAMBIOS SOCIALES Y PRÃCTICOS MUY BREVES, CON UN VOCABULARIO SUFICIENTE PARA HACER UNA EXPOSICIÃ“N O MANTENER UNA CONVERSACIÃ“N SENCILLA SOBRE TEMAS TÃ‰CNICOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(54,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÃCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','PARTICIPAR EN EL PROCESO DE NEGOCIACIÃ“N DE TECNOLOGÃA INFORMÃTICA PARA PERMITIR LA IMPLEMENTACIÃ“N DEL SISTEMA DE INFORMACIÃ“N.','ELABORAR EL INFORME SOBRE EL CUMPLIMIENTO DE LOS TÃ‰RMINOS DE REFERENCIAPREVISTOS EN LA NEGOCIACIÃ“N, DE ACUERDO CON LA PARTICIPACIÃ“N DE CADA UNODE LOS ACTORES EN RELACIÃ“N CON LA SATISFACCIÃ“N DE LOS BIENES INFORMÃTICOSCONTRATADOS Y RECIBIDOS, SEGÃšN NORMAS Y PROTOCOLOS DE LA ORGANIZACIÃ“N.','','0000-00-00','0000-00-00','Pendiente',''),(55,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÃCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','PRODUCIR TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y ORAL.','COMPRENDER LAS IDEAS PRINCIPALES DE TEXTOS COMPLEJOS EN INGLÃ‰S QUE TRATAN DE TEMAS TANTO CONCRETOS COMO ABSTRACTOS, INCLUSO SI SON DE CARÃCTER TÃ‰CNICO, SIEMPRE QUE ESTÃ‰N DENTRO DE SU CAMPO DE ESPECIALIZACIÃ“N','Clave','0000-00-00','0000-00-00','Pendiente',''),(56,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÃCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','PRODUCIR TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y ORAL.','LEER TEXTOS COMPLEJOS Y CON UN VOCABULARIO MÃS ESPECÃFICO, EN INGLÃ‰S GENERAL Y TÃ‰CNICO','Clave','0000-00-00','0000-00-00','Pendiente',''),(57,'IMPLANTACIÃ“N','DESARROLLAR LAS TAREAS DE CONFIGURACIÃ“N Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÃ“N.','APLICAR BUENAS PRÃCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','ELABORAR EL INFORME FINAL DEL PROCESO DE GESTIÃ“N DE CALIDAD EN ELDESARROLLO DE SOFTWARE, QUE CONSOLIDE LA INFORMACIÃ“N DE LAS EVIDENCIAS,HALLAZGOS Y NOVEDADES FRENTE AL SEGUIMIENTO Y CONTROL DE LOS PRODUCTOS,SEGÃšN NORMAS INTERNACIONALES Y PROTOCOLOS DE LA ORGANIZACIÃ“N..','','0000-00-00','0000-00-00','Pendiente',''),(58,'IMPLANTACIÃ“N','DESARROLLAR LAS TAREAS DE CONFIGURACIÃ“N Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÃ“N.','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÃ“N INFORMÃTICA.','EJECUTAR Y DOCUMENTAR LAS PRUEBAS DEL SOFTWARE, APLICANDO TÃ‰CNICAS DEENSAYO-ERROR, DE ACUERDO CON EL PLAN DISEÃ‘ADO Y LOS PROCEDIMIENTOSESTABLECIDOS POR LA EMPRESA','','0000-00-00','0000-00-00','Pendiente',''),(59,'IMPLANTACIÃ“N','DESARROLLAR LAS TAREAS DE CONFIGURACIÃ“N Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÃ“N.','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÃ“N INFORMÃTICA.','ELABORAR EL MANUAL TÃ‰CNICO DE LA APLICACIÃ“N, DE ACUERDO CON LACOMPLEJIDAD DEL APLICATIVO Y SEGÃšN NORMAS Y PROCEDIMIENTOS ESTABLECIDOSPOR LA EMPRESA.','','0000-00-00','0000-00-00','Pendiente',''),(60,'IMPLANTACIÃ“N','DESARROLLAR LAS TAREAS DE CONFIGURACIÃ“N Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÃ“N.','IMPLANTAR LA SOLUCIÃ“N QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÃ“N.','CAPACITAR A LOS USUARIOS DEL SISTEMA, SOBRE LA ESTRUCTURACIÃ“N Y EL MANEJODEL APLICATIVO, DE ACUERDO CON EL PLAN ESTABLECIDO, EL PERFIL DE LOSUSUARIOS, SEGÃšN POLÃTICAS DE LA ORGANIZACIÃ“N','','0000-00-00','0000-00-00','Pendiente',''),(61,'IMPLANTACIÃ“N','DESARROLLAR LAS TAREAS DE CONFIGURACIÃ“N Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÃ“N.','IMPLANTAR LA SOLUCIÃ“N QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÃ“N.','CONFIGURAR EL SOFTWARE DE LA APLICACIÃ“N PARA CLIENTE Y SERVIDOR, MEDIANTELA UTILIZACIÃ“N DEL HARDWARE DISPONIBLE, EJECUTÃNDOLA EN LA PLATAFORMATECNOLÃ“GICA, SEGÃšN NORMAS Y PROTOCOLOS ESTABLECIDOS POR LA EMPRESA.','','0000-00-00','0000-00-00','Pendiente',''),(62,'IMPLANTACIÃ“N','DESARROLLAR LAS TAREAS DE CONFIGURACIÃ“N Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÃ“N.','PRODUCIR TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y ORAL.','ENCONTRAR Y UTILIZAR SIN ESFUERZO VOCABULARIO Y EXPRESIONES DE INGLÃ‰S TÃ‰CNICO EN ARTÃCULOS DE REVISTAS, LIBROS ESPECIALIZADOS, PÃGINAS WEB, ETC','Clave','0000-00-00','0000-00-00','Pendiente',''),(63,'IMPLANTACIÃ“N','DESARROLLAR LAS TAREAS DE CONFIGURACIÃ“N Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÃ“N.','PRODUCIR TEXTOS EN INGLÃ‰S EN FORMA ESCRITA Y ORAL.','RELACIONARSE CON HABLANTES NATIVOS EN UN GRADO SUFICIENTE DE FLUIDEZ Y NATURALIDAD, DE MODO QUE LA COMUNICACIÃ“N SE REALICE SIN ESFUERZO POR PARTE DE LOS INTERLOCUTORES','Clave','0000-00-00','0000-00-00','Pendiente',''),(64,'IMPLANTACIÃ“N','VALIDAR LOS PROCESOS DE IMPLANTACIÃ“N DEL SISTEMA DE INFORMACIÃ“N.','IMPLANTAR LA SOLUCIÃ“N QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÃ“N.','DEFINIR ESTRATEGIAS PARA LA VALIDACIÃ“N DE MANUALES DE USUARIO Y DEOPERACIÃ“N, RESPONDIENDO A LAS NECESIDADES Y SATISFACCIÃ“N DEL CLIENTE,FRENTE A LA SOLUCIÃ“N INFORMÃTICA PROPUESTA, SEGÃšN POLÃTICAS DE LAORGANIZACIÃ“N','','0000-00-00','0000-00-00','Pendiente',''),(65,'IMPLANTACIÃ“N','VALIDAR LOS PROCESOS DE IMPLANTACIÃ“N DEL SISTEMA DE INFORMACIÃ“N.','IMPLANTAR LA SOLUCIÃ“N QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÃ“N.','ELABORAR EL INFORME ADMINISTRATIVO, SIGUIENDO LOS PROTOCOLOS DE LAORGANIZACIÃ“N, BASADO EN LOS PLANES DE INSTALACIÃ“N, RESPALDO Y MIGRACIÃ“NDEL SISTEMA DE INFORMACIÃ“N, FACILITANDO LA OPERATIVIDAD Y MANTENIMIENTODE LA SOLUCIÃ“N INFORMÃTICA','','0000-00-00','0000-00-00','Pendiente',''),(66,'IMPLANTACIÃ“N','VALIDAR LOS PROCESOS DE IMPLANTACIÃ“N DEL SISTEMA DE INFORMACIÃ“N.','IMPLANTAR LA SOLUCIÃ“N QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÃ“N.','ELABORAR INFORMES TÃ‰CNICOS RELACIONADOS CON LA SOLUCIÃ“N INFORMÃTICAIMPLANTADA, DE ACUERDO CON LAS PROPUESTAS DE ALTERNATIVAS APLICADAS,TENIENDO EN CUENTA LAS TÃ‰CNICAS DE COMUNICACIÃ“N Y SEGÃšN NORMAS YPROTOCOLOS ESTABLECIDOS.','','0000-00-00','0000-00-00','Pendiente',''),(67,'EVALUACIÃ“N','APLICAR LAS COMPETENCIAS ADQUIRIDAS EN EL PROCESO DE FORMACIÃ“N EN LA ETAPA LECTIVA.','RESULTADOS DE APRENDIZAJE ETAPA PRACTICA','APLICAR EN LA RESOLUCIÃ“N DE PROBLEMAS REALES DEL SECTOR PRODUCTIVO, LOS CONOCIMIENTOS, HABILIDADES Y DESTREZAS PERTINENTES A LAS COMPETENCIAS DEL PROGRAMA DE FORMACIÃ“N ASUMIENDO ESTRATEGIAS Y METODOLOGÃAS DE AUTOGESTIÃ“N','','0000-00-00','0000-00-00','Pendiente','');

/*Table structure for table `resultado_programa` */

DROP TABLE IF EXISTS `resultado_programa`;

CREATE TABLE `resultado_programa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `resultado_id` int(11) DEFAULT NULL,
  `programa_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `programa_id` (`programa_id`),
  KEY `resultado_id` (`resultado_id`),
  CONSTRAINT `resultado_programa_ibfk_1` FOREIGN KEY (`programa_id`) REFERENCES `programa` (`id_programa`),
  CONSTRAINT `resultado_programa_ibfk_2` FOREIGN KEY (`resultado_id`) REFERENCES `resultado_aprendizaje` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `resultado_programa` */

/*Table structure for table `seguimiento` */

DROP TABLE IF EXISTS `seguimiento`;

CREATE TABLE `seguimiento` (
  `segui_id` int(11) NOT NULL AUTO_INCREMENT,
  `estado_resultado` enum('evaluado','pendiente por evaluar','finalizado') DEFAULT NULL,
  `segui_ficha` int(11) DEFAULT NULL,
  `segui_rap` int(11) DEFAULT NULL,
  PRIMARY KEY (`segui_id`),
  KEY `segui_ficha` (`segui_ficha`),
  KEY `segui_rap` (`segui_rap`),
  CONSTRAINT `seguimiento_ibfk_1` FOREIGN KEY (`segui_ficha`) REFERENCES `fichas` (`id_ficha`),
  CONSTRAINT `seguimiento_ibfk_2` FOREIGN KEY (`segui_rap`) REFERENCES `resultado_programa` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `seguimiento` */

/*Table structure for table `usuarios` */

DROP TABLE IF EXISTS `usuarios`;

CREATE TABLE `usuarios` (
  `id_usuario` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(30) DEFAULT NULL,
  `apellido` varchar(30) DEFAULT NULL,
  `usuario` varchar(30) DEFAULT NULL,
  `pw` varchar(20) DEFAULT NULL,
  `rol` enum('administrador','instructor','coordinador') DEFAULT NULL,
  `correo` varchar(50) DEFAULT NULL,
  `telefono` varchar(10) DEFAULT NULL,
  `permiso1` tinyint(1) DEFAULT NULL,
  `permiso2` tinyint(1) DEFAULT NULL,
  `permiso3` tinyint(1) DEFAULT NULL,
  `permiso4` tinyint(1) DEFAULT NULL,
  `permiso5` tinyint(1) DEFAULT NULL,
  `permiso6` tinyint(1) DEFAULT NULL,
  `permiso7` tinyint(1) DEFAULT NULL,
  `permiso8` tinyint(1) DEFAULT NULL,
  `permiso9` tinyint(1) DEFAULT NULL,
  `permiso10` tinyint(1) DEFAULT NULL,
  `permiso11` tinyint(1) DEFAULT NULL,
  `permiso12` tinyint(1) DEFAULT NULL,
  `permiso13` tinyint(1) DEFAULT NULL,
  `permiso14` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4;

/*Data for the table `usuarios` */

insert  into `usuarios`(`id_usuario`,`nombre`,`apellido`,`usuario`,`pw`,`rol`,`correo`,`telefono`,`permiso1`,`permiso2`,`permiso3`,`permiso4`,`permiso5`,`permiso6`,`permiso7`,`permiso8`,`permiso9`,`permiso10`,`permiso11`,`permiso12`,`permiso13`,`permiso14`) values (2,'Andres ','Amaya Paez','Andres','123','administrador','andresamayap123123@gmail.com','3125724378',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(4,'Jose Davidad','Montesino Hoyos','Josedavid123','123','instructor','josedavid@gmail.com','111111111',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(5,'Linley Catalina','Moscote','LinleyMoscote','1234','instructor','linley123@gmail.com','12321312',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(6,'Karina','Meza','KarinaMeza','123','instructor','karinameza@gmail.com','2156465465',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(7,'Carlos','Mendoza','Carlomendoza','1233','instructor','carlosmendoza@gmail.com','657894489',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
