/*
SQLyog Community Edition- MySQL GUI v6.07
Host - 5.5.5-10.4.20-MariaDB : Database - login
*********************************************************************
Server version : 5.5.5-10.4.20-MariaDB
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

create database if not exists `login`;

USE `login`;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*Table structure for table `centro` */

DROP TABLE IF EXISTS `centro`;

CREATE TABLE `centro` (
  `centro_id` int(11) NOT NULL AUTO_INCREMENT,
  `centro_nombre` varchar(100) DEFAULT NULL,
  `centro_direccion` varchar(30) DEFAULT NULL,
  `centro_telefono` int(10) DEFAULT NULL,
  `centro_regional` int(11) DEFAULT NULL,
  PRIMARY KEY (`centro_id`),
  KEY `centro_regional` (`centro_regional`),
  CONSTRAINT `centro_ibfk_1` FOREIGN KEY (`centro_regional`) REFERENCES `regional` (`reg_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `centro` */

/*Table structure for table `centro_tiene_programa` */

DROP TABLE IF EXISTS `centro_tiene_programa`;

CREATE TABLE `centro_tiene_programa` (
  `centroprograma_id` int(11) NOT NULL AUTO_INCREMENT,
  `centro_id` int(11) DEFAULT NULL,
  `progra_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`centroprograma_id`),
  KEY `centro_id` (`centro_id`),
  KEY `progra_id` (`progra_id`),
  CONSTRAINT `centro_tiene_programa_ibfk_1` FOREIGN KEY (`centro_id`) REFERENCES `centro` (`centro_id`),
  CONSTRAINT `centro_tiene_programa_ibfk_2` FOREIGN KEY (`progra_id`) REFERENCES `programa` (`id_programa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `centro_tiene_programa` */

/*Table structure for table `competencia` */

DROP TABLE IF EXISTS `competencia`;

CREATE TABLE `competencia` (
  `comp_id` int(11) NOT NULL AUTO_INCREMENT,
  `comp_nombre` varchar(100) DEFAULT NULL,
  `comp_horas` int(11) DEFAULT NULL,
  `comp_programa` int(11) DEFAULT NULL,
  PRIMARY KEY (`comp_id`),
  KEY `comp_programa` (`comp_programa`),
  CONSTRAINT `competencia_ibfk_1` FOREIGN KEY (`comp_programa`) REFERENCES `programa` (`id_programa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `competencia` */

/*Table structure for table `fase` */

DROP TABLE IF EXISTS `fase`;

CREATE TABLE `fase` (
  `fase_id` int(11) NOT NULL AUTO_INCREMENT,
  `fase_nombre` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`fase_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `fase` */

/*Table structure for table `fichas` */

DROP TABLE IF EXISTS `fichas`;

CREATE TABLE `fichas` (
  `id_ficha` int(11) NOT NULL,
  `tipo_programa` enum('especializacion','tecnologo','tecnico') DEFAULT NULL,
  `nombre_programa` int(11) NOT NULL,
  `lider_ficha` int(11) NOT NULL,
  PRIMARY KEY (`id_ficha`),
  KEY `nombre_programa` (`nombre_programa`),
  KEY `lider_ficha` (`lider_ficha`),
  CONSTRAINT `fichas_ibfk_1` FOREIGN KEY (`nombre_programa`) REFERENCES `programa` (`id_programa`),
  CONSTRAINT `fichas_ibfk_2` FOREIGN KEY (`lider_ficha`) REFERENCES `usuarios` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `fichas` */

insert  into `fichas`(`id_ficha`,`tipo_programa`,`nombre_programa`,`lider_ficha`) values (12313,'tecnico',1,6),(245646,'especializacion',2,4),(1231313,'tecnologo',1,5),(2068060,'tecnologo',1,4),(2435346,'tecnologo',2,7);

/*Table structure for table `programa` */

DROP TABLE IF EXISTS `programa`;

CREATE TABLE `programa` (
  `id_programa` int(11) NOT NULL AUTO_INCREMENT,
  `pro_nombre` varchar(50) NOT NULL,
  PRIMARY KEY (`id_programa`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

/*Data for the table `programa` */

insert  into `programa`(`id_programa`,`pro_nombre`) values (1,'Adsi'),(2,'Ingles'),(8,'ganaderia');

/*Table structure for table `rap` */

DROP TABLE IF EXISTS `rap`;

CREATE TABLE `rap` (
  `rap_id` int(11) NOT NULL AUTO_INCREMENT,
  `rap_nombre` varchar(1000) DEFAULT NULL,
  `rap_resultado` varchar(1000) DEFAULT NULL,
  `rap_inicio` date DEFAULT NULL,
  `rap_fin` date DEFAULT NULL,
  `rap_horas` int(11) DEFAULT NULL,
  `rap_competencia` int(11) DEFAULT NULL,
  `rap_fase` int(11) DEFAULT NULL,
  PRIMARY KEY (`rap_id`),
  KEY `rap_competencia` (`rap_competencia`),
  KEY `rap_fase` (`rap_fase`),
  CONSTRAINT `rap_ibfk_1` FOREIGN KEY (`rap_competencia`) REFERENCES `competencia` (`comp_id`),
  CONSTRAINT `rap_ibfk_2` FOREIGN KEY (`rap_fase`) REFERENCES `fase` (`fase_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `rap` */

/*Table structure for table `regional` */

DROP TABLE IF EXISTS `regional`;

CREATE TABLE `regional` (
  `reg_id` int(11) NOT NULL AUTO_INCREMENT,
  `reg_nombre` varchar(100) DEFAULT NULL,
  `reg_direccion` varchar(30) DEFAULT NULL,
  `reg_telefono` int(10) DEFAULT NULL,
  `reg_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`reg_id`),
  KEY `reg_usuario` (`reg_usuario`),
  CONSTRAINT `regional_ibfk_1` FOREIGN KEY (`reg_usuario`) REFERENCES `usuarios` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `regional` */

/*Table structure for table `resultado_aprendizaje` */

DROP TABLE IF EXISTS `resultado_aprendizaje`;

CREATE TABLE `resultado_aprendizaje` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ficha_id` int(11) DEFAULT NULL,
  `fase` varchar(20) DEFAULT NULL,
  `actividad` varchar(200) DEFAULT NULL,
  `competencia` varchar(500) DEFAULT NULL,
  `resultado` varchar(500) DEFAULT NULL,
  `tipo` enum('Clave','Transversal','Específico','Institucional') DEFAULT NULL,
  `fecha_inicio` date DEFAULT NULL,
  `fecha_fin` date DEFAULT NULL,
  `estado` enum('Evaluado','Pendiente','En ejecución') DEFAULT NULL,
  `observaciones` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ficha_id` (`ficha_id`),
  CONSTRAINT `resultado_aprendizaje_ibfk_1` FOREIGN KEY (`ficha_id`) REFERENCES `fichas` (`id_ficha`)
) ENGINE=InnoDB AUTO_INCREMENT=2435609 DEFAULT CHARSET=latin1;

/*Data for the table `resultado_aprendizaje` */

insert  into `resultado_aprendizaje`(`id`,`ficha_id`,`fase`,`actividad`,`competencia`,`resultado`,`tipo`,`fecha_inicio`,`fecha_fin`,`estado`,`observaciones`) values (12313,NULL,'INDUCCIÓN','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÒN PROFESIONAL INTEGRAL Y PRESENTACIÓN DEL PROYECTO FORMATIVO','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','ASUMIR LOS DEBERES Y DERECHOS CON BASE EN LAS LEYES Y LA NORMATIVA INSTITUCIONAL EN EL MARCO DE SU PROYECTO DE VIDA.','Institucional','0000-00-00','0000-00-00','Evaluado','José Montesino'),(2435540,12313,'asdad','asdad','asdsad','adad','Específico','0000-00-00','0012-03-12','Pendiente',''),(2435541,12313,'123122412','42134124','214214','12adsa','Institucional','0032-12-12','0312-03-12','Evaluado',''),(2435542,12313,'INDUCCIÓN','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÒN PROFESIONAL INTEGRAL Y PRESENTACIÓN DEL PROYECTO FORMATIVO','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','CONCERTAR ALTERNATIVAS Y ACCIONES DE FORMACIÓN PARA EL DESARROLLO DE LAS COMPETENCIAS DEL PROGRAMA FORMACIÓN, CON BASE EN LA POLÍTICA INSTITUCIONAL.','Institucional','0000-00-00','0000-00-00','Evaluado','José Montesino'),(2435543,12313,'INDUCCIÓN','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÒN PROFESIONAL INTEGRAL Y PRESENTACIÓN DEL PROYECTO FORMATIVO','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','GESTIONAR LA INFORMACIÓN DE ACUERDO CON LOS PROCEDIMIENTOS ESTABLECIDOS Y CON LAS TECNOLOGÍAS DE LA INFORMACIÓN Y LA COMUNICACIÓN DISPONIBLES.','Institucional','0000-00-00','0000-00-00','Evaluado','José Montesino'),(2435544,12313,'INDUCCIÓN','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÒN PROFESIONAL INTEGRAL Y PRESENTACIÓN DEL PROYECTO FORMATIVO','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','IDENTIFICAR LAS OPORTUNIDADES QUE EL SENA OFRECE EN EL MARCO DE LA FORMACIÓN PROFESIONAL DE ACUERDO CON EL CONTEXTO NACIONAL E INTERNACIONAL.','Institucional','0000-00-00','0000-00-00','Evaluado','José Montesino'),(2435545,12313,'INDUCCIÓN','IDENTIFICAR LOS LINEAMIENTOS INSTITUCIONALES RELACIONADOS CON LA FORMACIÒN PROFESIONAL INTEGRAL Y PRESENTACIÓN DEL PROYECTO FORMATIVO','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','RECONOCER EL ROL DE LOS PARTICIPANTES EN EL PROCESO FORMATIVO, EL PAPEL DE LOS AMBIENTES DE APRENDIZAJE Y LA METODOLOGÍA DE FORMACIÓN, DE ACUERDO CON LA DINÁMICA ORGANIZACIONAL DEL SENA','Institucional','0000-00-00','0000-00-00','Evaluado','José Montesino'),(2435546,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','INTERPRETAR EL INFORME DE REQUERIMIENTOS, PARA DETERMINAR LASNECESIDADES TECNOLÓGICAS EN EL MANEJO DE LA INFORMACIÓN, DE ACUERDOCON LAS NORMAS Y PROTOCOLOS ESTABLECIDOS EN LA EMPRESA','Específico','0000-00-00','0000-00-00','Evaluado','Linley Moscote'),(2435547,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','VALORAR LA INCIDENCIA DE LOS DATOS EN LOS PROCESOS DEL MACROSISTEMA,TOMANDO COMO REFERENTE EL DICCIONARIO DE DATOS Y LASMINIESPECIFICACIONES, PARA LA CONSOLIDACIÓN DE LOS DATOS QUE INTERVIENEN,DE ACUERDO CON PARÁMETROS ESTABLECIDOS.','Específico','0000-00-00','0000-00-00','En ejecución','Julian Trespalacios'),(2435548,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','APLICAR BUENAS PRÁCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','IDENTIFICAR LAS CARACTERÍSTICAS DE LOS PROCESOS DE DESARROLLO DESOFTWARE, FRENTE AL REFERENTE DE CALIDAD ADOPTADO POR LA EMPRESA,AJUSTÁNDOLOS A LOS RESULTADOS DE LAS MEDICIONES, EVALUACIONES YRECOMENDACIONES REALIZADAS','Específico','0000-00-00','0000-00-00','Evaluado','Maira Diaz'),(2435549,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','COMPRENDER TEXTOS EN INGLÉS EN FORMA ESCRITA Y AUDITIVA','COMPRENDER FRASES Y VOCABULARIO HABITUAL SOBRE TEMAS DE INTERÉS PERSONAL Y TEMAS TÉCNICOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435550,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','COMPRENDER TEXTOS EN INGLÉS EN FORMA ESCRITA Y AUDITIVA','COMPRENDER LA IDEA PRINCIPAL EN AVISOS Y MENSAJES BREVES, CLAROS Y SENCILLOS EN INGLÉS TÉCNICO','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435551,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','ESPECIFICAR LOS REQUISITOS NECESARIOS PARA DESARROLLAR EL SISTEMA DE INFORMACION DE ACUERDO CON LAS NECESIDADES DEL CLIENTE.','APLICAR LAS TÉCNICAS DE RECOLECCIÓN DE DATOS , DISEÑANDO LOSINSTRUMENTOS NECESARIOS PARA EL PROCESAMIENTO DE INFORMACIÓN, DEACUERDO CON LA SITUACIÓN PLANTEADA POR LA EMPRESA','Específico','0000-00-00','0000-00-00','Evaluado','\"Linley Moscote\r\n'),(2435552,12313,'(Los Aprendices no c','2068060','','\r\n','','0000-00-00','0000-00-00','',''),(2435553,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','ESPECIFICAR LOS REQUISITOS NECESARIOS PARA DESARROLLAR EL SISTEMA DE INFORMACION DE ACUERDO CON LAS NECESIDADES DEL CLIENTE.','ELABORAR MAPAS DE PROCESOS QUE PERMITAN IDENTIFICAR LAS ÁREASINVOLUCRADAS EN UN SISTEMA DE INFORMACIÓN, UTILIZANDO HERRAMIENTASINFORMÁTICAS Y LAS TIC’S, PARA GENERAR INFORMES SEGÚN LAS NECESIDADES DELA EMPRESA','Específico','0000-00-00','0000-00-00','Evaluado','Karina Meza'),(2435554,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','INTERACTUAR EN LOS CONTEXTOS PRODUCTIVOS Y SOCIALES EN FUNCIÓN DE LOS PRINCIPIOS Y VALORES UNIVERSALES.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(2435555,12313,'IDENTIFICACIÓN','DETERMINAR LAS ESPECIFICACIONES FUNCIONALES DEL SISTEMA DE INFORMACIÓN.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','REDIMENSIONAR PERMANENTEMENTE SU PROYECTO DE VIDA DE ACUERDO CON LAS CIRCUNSTANCIAS DEL CONTEXTO Y CON VISIÓN PROSPECTIVA.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(2435556,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','CONSTRUIR EL MODELO CONCEPTUAL DEL MACROSISTEMA FRENTE A LOSREQUERIMIENTOS DEL CLIENTE, MEDIANTE EL USO E INTERPRETACIÓN DE LAINFORMACIÓN LEVANTADA, REPRESENTADO EN DIAGRAMAS DE CLASE, DEINTERACCIÓN, COLABORACIÓN Y CONTRATOS DE OPERACIÓN, DE ACUERDO CON LASDIFERENTES SECUENCIAS, FASES Y PROCEDIMIENTOS DEL SISTEMA.','Específico','0000-00-00','0000-00-00','En ejecución','Maira Diaz'),(2435557,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','ELABORAR EL INFORME DE LOS RESULTADOS DEL ANÁLISIS DEL SISTEMA DEINFORMACIÓN, DE ACUERDO CON LOS REQUERIMIENTOS DEL CLIENTE SEGÚNNORMAS Y PROTOCOLOS ESTABLECIDOS.','Específico','0000-00-00','0000-00-00','Evaluado','Maira Diaz'),(2435558,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','ANALIZAR LOS REQUISITOS DEL CLIENTE PARA CONSTRUIR EL SISTEMA DE INFORMACION.','REPRESENTA EL BOSQUEJO DE LA SOLUCIÓN AL PROBLEMA PRESENTADO POR ELCLIENTE, MEDIANTE LA ELABORACIÓN DE DIAGRAMAS DE CASOS DE USO, APOYADOEN EL ANÁLISIS DEL INFORME DE REQUERIMIENTOS, AL CONFRONTAR LA SITUACIÓNPROBLEMICA CON EL USUARIO SEGÚN NORMAS Y PROTOCOLOS DE LA ORGANIZACIÓN','Específico','0000-00-00','0000-00-00','En ejecución','Maira Diaz'),(2435559,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','COMPRENDER TEXTOS EN INGLÉS EN FORMA ESCRITA Y AUDITIVA','LEER TEXTOS MUY BREVES Y SENCILLOS EN INGLÉS GENERAL Y TÉCNICO','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435560,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','ESPECIFICAR LOS REQUISITOS NECESARIOS PARA DESARROLLAR EL SISTEMA DE INFORMACION DE ACUERDO CON LAS NECESIDADES DEL CLIENTE.','PLANTEAR DIFERENTES ALTERNATIVAS, DE MODELOS TECNOLÓGICOS DE INFORMACIÓNEMPRESARIAL, TENIENDO EN CUENTA LA PLATAFORMA TECNOLÓGICA DE LA EMPRESAY LAS TENDENCIAS DEL MERCADO, PARA DAR SOLUCIÓN A LAS SITUACIONESRELACIONADAS CON EL MANEJO DE LA INFORMACIÓN DE LA ORGANIZACIÓN.','Específico','0000-00-00','0000-00-00','Pendiente','Jose Montesino'),(2435561,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','PARTICIPAR EN EL PROCESO DE NEGOCIACIÓN DE TECNOLOGÍA INFORMÁTICA PARA PERMITIR LA IMPLEMENTACIÓN DEL SISTEMA DE INFORMACIÓN.','INTERPRETAR EL DIAGNÓSTICO DE NECESIDADES INFORMÁTICAS, PARA DETERMINARLAS TECNOLÓGICAS REQUERIDAS EN EL MANEJO DE LA INFORMACIÓN, DE ACUERDOCON LAS NORMAS Y PROTOCOLOS ESTABLECIDOS POR LA EMPRESA.','Específico','0000-00-00','0000-00-00','En ejecución','Linley Moscote'),(2435562,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','PRODUCIR TEXTOS EN INGLÉS EN FORMA ESCRITA Y ORAL.','REPRODUCIR EN INGLÉS FRASES O ENUNCIADOS SIMPLES QUE PERMITAN EXPRESAR DE FORMA LENTA IDEAS O CONCEPTOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435563,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','DESARROLLAR PERMANENTEMENTE LAS HABILIDADES PSICOMOTRICES Y DE PENSAMIENTO EN LA EJECUCIÓN DE LOS PROCESOS DE APRENDIZAJE.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(2435564,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','GENERAR HÁBITOS SALUDABLES EN SU ESTILO DE VIDA PARA GARANTIZAR LA PREVENCIÓN DE RIESGOS OCUPACIONALES DE ACUERDO CON EL DIAGNÓSTICO DE SU CONDICIÓN FÍSICA INDIVIDUAL Y LA NATURALEZA Y COMPLEJIDAD DE SU DESEMPEÑO LABORAL.','Transversal','0000-00-00','0000-00-00','En ejecución','Maira Muñoz'),(2435565,12313,'ANÁLISIS','ANALIZAR LOS PROCESOS Y DATOS DEL SISTEMA DE INFORMACIÓN Y ESPECIFICAR EL MODELO CONCEPTUAL DEL SISTEMA DE INFORMACIÓN.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','GENERAR PROCESOS AUTÓNOMOS Y DE TRABAJO COLABORATIVO PERMANENTES, FORTALECIENDO EL EQUILIBRIO DE LOS COMPONENTES RACIONALES Y EMOCIONALES ORIENTADOS HACIA EL DESARROLLO HUMANO INTEGRAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(2435566,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','APLICAR BUENAS PRÁCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','IDENTIFICAR LOS PUNTOS CRÍTICOS DE CONTROL EN LOS PROCESOS DE DESARROLLODE SOFTWARE, PARA ESTABLECER LAS ACCIONES A SEGUIR, GARANTIZANDO ELCUMPLIMIENTO DE LOS ESTÁNDARES DE CALIDAD, SIGUIENDO LOS LINEAMIENTOSESTABLECIDOS POR LA ORGANIZACIÓN','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435567,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','COMPRENDER TEXTOS EN INGLÉS EN FORMA ESCRITA Y AUDITIVA','ENCONTRAR INFORMACIÓN ESPECÍFICA Y PREDECIBLE EN ESCRITOS SENCILLOS Y COTIDIANOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435568,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','COMPRENDER TEXTOS EN INGLÉS EN FORMA ESCRITA Y AUDITIVA','ENCONTRAR VOCABULARIO Y EXPRESIONES DE INGLÉS TÉCNICO EN ANUNCIOS, FOLLETOS, PÁGINAS WEB, ETC','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435569,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','DISEÑAR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','CONSTRUIR EL PROTOTIPO DEL SISTEMA DE INFORMACIÓN, A PARTIR DEL ANÁLISIS DELAS CARACTERÍSTICAS FUNCIONALES DEL SISTEMA EN RELACIÓN CON FACILIDAD DEMANEJO, FUNCIONALIDAD Y EXPERIENCIA DEL USUARIO, APOYADO EN SOFTWAREAPLICADO SEGÚN PROTOCOLOS DE DISEÑO.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435570,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','DISEÑAR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','DISEÑAR LA ARQUITECTURA DEL SOFTWARE, MEDIANTE LA INTERPRETACIÓN DE LASCLASES, OBJETOS Y MECANISMOS DE COLABORACIÓN, UTILIZANDO HERRAMIENTASTECNOLÓGICAS DE DISEÑO, DE ACUERDO CON LAS TENDENCIAS DE LASTECNOLOGÍAS DE LA INFORMACIÓN Y LA COMUNICACIÓN.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435571,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','DISEÑAR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','DISEÑAR LA ARQUITECTURA TECNOLÓGICA DEL SISTEMA DE INFORMACIÓN, MEDIANTEEL RECONOCIMIENTO DE HARDWARE Y SOFTWARE, DE ACUERDO CON LA TECNOLOGÍADISPONIBLE EN EL MERCADO, EL INFORME DE ANÁLISIS LEVANTADO Y EL DIAGRAMADE DISTRIBUCIÓN','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435572,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','DISEÑAR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','DISEÑAR LA ESTRUCTURA DE DATOS, A PARTIR DEL MODELO CONCEPTUALDETERMINADO EN EL ANÁLISIS DEL SISTEMA, UTILIZANDO HERRAMIENTASTECNOLÓGICAS DE BASES DE DATOS, SEGÚN LAS NORMAS Y ESTÁNDARESESTABLECIDOS','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435573,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','DISEÑAR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','ELABORAR EL INFORME DE DISEÑO DEL SISTEMA DE INFORMACIÓN, DE ACUERDOCON LA SELECCIÓN DE LAS HERRAMIENTAS, TANTO DE SOFTWARE COMO DEHARDWARE, REQUERIDAS PARA LA SOLUCIÓN INFORMÁTICA.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435574,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','PARTICIPAR EN EL PROCESO DE NEGOCIACIÓN DE TECNOLOGÍA INFORMÁTICA PARA PERMITIR LA IMPLEMENTACIÓN DEL SISTEMA DE INFORMACIÓN.','DEFINIR ESTRATEGIAS PARA LA ELABORACIÓN DE TÉRMINOS DE REFERENCIA YPROCESOS DE EVALUACIÓN DE PROVEEDORES, EN LA ADQUISICIÓN DE TECNOLOGÍA,SEGÚN PROTOCOLOS ESTABLECIDOS.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435575,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','PARTICIPAR EN EL PROCESO DE NEGOCIACIÓN DE TECNOLOGÍA INFORMÁTICA PARA PERMITIR LA IMPLEMENTACIÓN DEL SISTEMA DE INFORMACIÓN.','PARTICIPAR EN LOS PERFECCIONAMIENTOS DE CONTRATOS INFORMÁTICOS,ESTABLECIENDO CLÁUSULAS TÉCNICAS, QUE RESPONDAN A LAS NECESIDADES DELOS ACTORES DE LA NEGOCIACIÓN, DE ACUERDO CON LA LEY DE CONTRATACIÓN','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435576,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','PRODUCIR TEXTOS EN INGLÉS EN FORMA ESCRITA Y ORAL.','COMPRENDER UNA AMPLIA VARIEDAD DE FRASES Y VOCABULARIO  EN INGLÉS SOBRE TEMAS DE INTERÉS PERSONAL Y TEMAS TÉCNICOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435577,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','PRODUCIR TEXTOS EN INGLÉS EN FORMA ESCRITA Y ORAL.','IDENTIFICAR FORMAS GRAMATICALES BÁSICAS EN TEXTOS Y DOCUMENTOS ELEMENTALES ESCRITOS EN INGLÉS','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435578,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','ASUMIR ACTITUDES CRÍTICAS , ARGUMENTATIVAS Y PROPOSITIVAS EN FUNCIÓN DE LA RESOLUCIÓN DE PROBLEMAS DE CARÁCTER PRODUCTIVO Y SOCIAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(2435579,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','ASUMIR RESPONSABLEMENTE LOS CRITERIOS DE PRESERVACIÓN Y CONSERVACIÓN DEL MEDIO AMBIENTE Y DE DESARROLLO SOSTENIBLE, EN EL EJERCICIO DE SU DESEMPEÑO LABORAL Y SOCIAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(2435580,12313,'DISEÑO','DETERMINAR LA ESTRUCTURA LÓGICA DEL SISTEMA DE INFORMACIÓN','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','DESARROLLAR PROCESOS COMUNICATIVOS EFICACES Y ASERTIVOS DENTRO DE CRITERIOS DE RACIONALIDAD QUE POSIBILITEN LA CONVIVENCIA, EL ESTABLECIMIENTO DE ACUERDOS, LA CONSTRUCCIÓN COLECTIVA DEL CONOCIMIENTO Y LA RESOLUCIÓN DE PROBLEMAS DE CARÁCTER PRODUCTIVO Y SOCIAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(2435581,12313,'DESARROLLO','CODIFICAR LOS MÓDULOS DEL SISTEMA DE INFORMACIÓN.','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÓN INFORMÁTICA.','CONSTRUIR EL PROGRAMA DE INSTALACIÓN DEL APLICATIVO, UTILIZANDO LASHERRAMIENTAS DE DESARROLLO DISPONIBLES EN EL MERCADO, SEGÚN LASCARACTERÍSTICAS DE LA ARQUITECTURA DE LA SOLUCIÓN','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435582,12313,'DESARROLLO','CODIFICAR LOS MÓDULOS DEL SISTEMA DE INFORMACIÓN.','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÓN INFORMÁTICA.','REALIZAR LA CODIFICACIÓN DE LOS MÓDULOS DEL SISTEMA Y EL PROGRAMAPRINCIPAL, A PARTIR DE LA UTILIZACIÓN DEL LENGUAJE DE PROGRAMACIÓNSELECCIONADO, DE ACUERDO CON LAS ESPECIFICACIONES DEL DISEÑO','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435583,12313,'DESARROLLO','CODIFICAR LOS MÓDULOS DEL SISTEMA DE INFORMACIÓN.','PROMOVER LA INTERACCION IDONEA CONSIGO MISMO, CON LOS DEMAS Y CON LA NATURALEZA EN LOS CONTEXTOS LABORAL Y SOCIAL.','APLICAR TÉCNICAS DE CULTURA FÍSICA PARA EL MEJORAMIENTO DE SU EXPRESIÓN CORPORAL, DESEMPEÑO LABORAL SEGÚN LA NATURALEZA Y COMPLEJIDAD DEL ÁREA OCUPACIONAL.','Transversal','0000-00-00','0000-00-00','Pendiente',''),(2435584,12313,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','APLICAR BUENAS PRÁCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','APLICAR LOS ESTÁNDARES DE CALIDAD INVOLUCRADOS EN LOS PROCESOS DEDESARROLLO DE SOFTWARE, SIGUIENDO EL PLAN ESTABLECIDO PARA MANTENER LAINTEGRIDAD DE LOS PRODUCTOS DE TRABAJO DEFINIDOS, SEGÚN LAS PRÁCTICASDE CONFIGURACIÓN ESTABLECIDAS POR LA EMPRESA','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435585,12313,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','COMPRENDER TEXTOS EN INGLÉS EN FORMA ESCRITA Y AUDITIVA','COMUNICARSE EN TAREAS SENCILLAS Y HABITUALES QUE REQUIEREN UN INTERCAMBIO SIMPLE Y DIRECTO DE INFORMACIÓN COTIDIANA Y TÉCNICA','Clave','0000-00-00','0000-00-00','En ejecución','Carlos Mendoza'),(2435586,12313,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÓN INFORMÁTICA.','CONSTRUIR LA BASE DE DATOS, A PARTIR DEL MODELO DE DATOS DETERMINADO ENEL DISEÑO DEL SISTEMA, UTILIZANDO SISTEMAS DE GESTIÓN DE BASE DE DATOS,SEGÚN LOS PROTOCOLOS ESTABLECIDOS EN LA ORGANIZACIÓN','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435587,12313,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÓN INFORMÁTICA.','CONSTRUIR LA INTERFAZ DE USUARIO, APOYADO EN LA EVALUACIÓN DEL PROTOTIPO,DETERMINANDO LAS ENTRADAS Y SALIDAS REQUERIDAS EN EL DISEÑO Y DEFINIENDOLOS LINEAMIENTOS PARA LA NAVEGACIÓN, DE ACUERDO CON LAS NECESIDADES DELUSUARIO','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435588,12313,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÓN INFORMÁTICA.','INTERPRETAR EL INFORME TÉCNICO DE DISEÑO, PARA DETERMINAR EL PLAN DETRABAJO DURANTE LA FASE DE CONSTRUCCIÓN DEL SOFTWARE, DE ACUERDO CON LASNORMAS Y PROTOCOLOS ESTABLECIDOS EN LA EMPRESA.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435589,12313,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','DISEÑAR EL SISTEMA DE ACUERDO CON LOS REQUISITOS DEL CLIENTE.','APLICAR POLÍTICAS Y MECANISMOS DE CONTROL EN EL DISEÑO DEL SISTEMA DEINFORMACIÓN, MEDIANTE EL ANÁLISIS DE LA VULNERABILIDAD DE LA INFORMACIÓN,SIGUIENDO LOS PARÁMETROS ESTABLECIDOS POR LA ORGANIZACIÓN.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435590,12313,'DESARROLLO','DESARROLLAR LA ESTRUCTURA DE DATOS Y LA INTERFAZ DE USUARIO','PRODUCIR TEXTOS EN INGLÉS EN FORMA ESCRITA Y ORAL.','BUSCAR DE MANERA SISTEMÁTICA INFORMACIÓN ESPECÍFICA Y DETALLADA EN ESCRITOS EN INGLÉS, MAS ESTRUCTURADOS Y CON MAYOR CONTENIDO TÉCNICO','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435591,12313,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÁCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','APLICAR BUENAS PRÁCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','ELABORAR INSTRUMENTOS E INSTRUCTIVOS, REQUERIDOS POR EL ASEGURAMIENTODE LA CALIDAD, PARA DOCUMENTAR Y EVALUAR LOS PROCESOS DE DESARROLLO DESOFTWARE, DE ACUERDO CON LAS NORMAS Y PROCEDIMIENTOS ESTABLECIDASPOR LA EMPRESA','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435592,12313,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÁCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','APLICAR BUENAS PRÁCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','EVALUAR PROCESOS Y PRODUCTOS DE DESARROLLO DE SOFTWARE, DOCUMENTAR YCONCERTAR ACCIONES A SEGUIR, PARA GARANTIZAR EL CUMPLIMIENTO DE LASNORMAS ESTABLECIDAS, DE ACUERDO CON EL PLAN DEFINIDO Y CON LOS CRITERIOSDE MEDICIÓN, MÉTRICAS Y POLÍTICAS DETERMINADOS POR LA EMPRESA','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435593,12313,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÁCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','COMPRENDER TEXTOS EN INGLÉS EN FORMA ESCRITA Y AUDITIVA','REALIZAR INTERCAMBIOS SOCIALES Y PRÁCTICOS MUY BREVES, CON UN VOCABULARIO SUFICIENTE PARA HACER UNA EXPOSICIÓN O MANTENER UNA CONVERSACIÓN SENCILLA SOBRE TEMAS TÉCNICOS','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435594,12313,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÁCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','PARTICIPAR EN EL PROCESO DE NEGOCIACIÓN DE TECNOLOGÍA INFORMÁTICA PARA PERMITIR LA IMPLEMENTACIÓN DEL SISTEMA DE INFORMACIÓN.','ELABORAR EL INFORME SOBRE EL CUMPLIMIENTO DE LOS TÉRMINOS DE REFERENCIAPREVISTOS EN LA NEGOCIACIÓN, DE ACUERDO CON LA PARTICIPACIÓN DE CADA UNODE LOS ACTORES EN RELACIÓN CON LA SATISFACCIÓN DE LOS BIENES INFORMÁTICOSCONTRATADOS Y RECIBIDOS, SEGÚN NORMAS Y PROTOCOLOS DE LA ORGANIZACIÓN.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435595,12313,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÁCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','PRODUCIR TEXTOS EN INGLÉS EN FORMA ESCRITA Y ORAL.','COMPRENDER LAS IDEAS PRINCIPALES DE TEXTOS COMPLEJOS EN INGLÉS QUE TRATAN DE TEMAS TANTO CONCRETOS COMO ABSTRACTOS, INCLUSO SI SON DE CARÁCTER TÉCNICO, SIEMPRE QUE ESTÉN DENTRO DE SU CAMPO DE ESPECIALIZACIÓN','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435596,12313,'DESARROLLO','DETERMINAR EL CUMPLIMIENTO DE LAS BUENAS PRÁCTICAS DE CALIDAD EN EL DESARROLLO DE SOFTWARE','PRODUCIR TEXTOS EN INGLÉS EN FORMA ESCRITA Y ORAL.','LEER TEXTOS COMPLEJOS Y CON UN VOCABULARIO MÁS ESPECÍFICO, EN INGLÉS GENERAL Y TÉCNICO','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435597,12313,'IMPLANTACIÓN','DESARROLLAR LAS TAREAS DE CONFIGURACIÓN Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÓN.','APLICAR BUENAS PRÁCTICAS DE CALIDAD EN EL PROCESO DE DESARROLLO DE SOFTWARE, DE ACUERDO CON EL REFERENTE ADOPTADO EN LA EMPRESA.','ELABORAR EL INFORME FINAL DEL PROCESO DE GESTIÓN DE CALIDAD EN ELDESARROLLO DE SOFTWARE, QUE CONSOLIDE LA INFORMACIÓN DE LAS EVIDENCIAS,HALLAZGOS Y NOVEDADES FRENTE AL SEGUIMIENTO Y CONTROL DE LOS PRODUCTOS,SEGÚN NORMAS INTERNACIONALES Y PROTOCOLOS DE LA ORGANIZACIÓN..','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435598,12313,'IMPLANTACIÓN','DESARROLLAR LAS TAREAS DE CONFIGURACIÓN Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÓN.','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÓN INFORMÁTICA.','EJECUTAR Y DOCUMENTAR LAS PRUEBAS DEL SOFTWARE, APLICANDO TÉCNICAS DEENSAYO-ERROR, DE ACUERDO CON EL PLAN DISEÑADO Y LOS PROCEDIMIENTOSESTABLECIDOS POR LA EMPRESA','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435599,12313,'IMPLANTACIÓN','DESARROLLAR LAS TAREAS DE CONFIGURACIÓN Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÓN.','CONSTRUIR EL SISTEMA QUE CUMPLA CON LOS REQUISITOS DE LA SOLUCIÓN INFORMÁTICA.','ELABORAR EL MANUAL TÉCNICO DE LA APLICACIÓN, DE ACUERDO CON LACOMPLEJIDAD DEL APLICATIVO Y SEGÚN NORMAS Y PROCEDIMIENTOS ESTABLECIDOSPOR LA EMPRESA.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435600,12313,'IMPLANTACIÓN','DESARROLLAR LAS TAREAS DE CONFIGURACIÓN Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÓN.','IMPLANTAR LA SOLUCIÓN QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÓN.','CAPACITAR A LOS USUARIOS DEL SISTEMA, SOBRE LA ESTRUCTURACIÓN Y EL MANEJODEL APLICATIVO, DE ACUERDO CON EL PLAN ESTABLECIDO, EL PERFIL DE LOSUSUARIOS, SEGÚN POLÍTICAS DE LA ORGANIZACIÓN','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435601,12313,'IMPLANTACIÓN','DESARROLLAR LAS TAREAS DE CONFIGURACIÓN Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÓN.','IMPLANTAR LA SOLUCIÓN QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÓN.','CONFIGURAR EL SOFTWARE DE LA APLICACIÓN PARA CLIENTE Y SERVIDOR, MEDIANTELA UTILIZACIÓN DEL HARDWARE DISPONIBLE, EJECUTÁNDOLA EN LA PLATAFORMATECNOLÓGICA, SEGÚN NORMAS Y PROTOCOLOS ESTABLECIDOS POR LA EMPRESA.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435602,12313,'IMPLANTACIÓN','DESARROLLAR LAS TAREAS DE CONFIGURACIÓN Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÓN.','PRODUCIR TEXTOS EN INGLÉS EN FORMA ESCRITA Y ORAL.','ENCONTRAR Y UTILIZAR SIN ESFUERZO VOCABULARIO Y EXPRESIONES DE INGLÉS TÉCNICO EN ARTÍCULOS DE REVISTAS, LIBROS ESPECIALIZADOS, PÁGINAS WEB, ETC','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435603,12313,'IMPLANTACIÓN','DESARROLLAR LAS TAREAS DE CONFIGURACIÓN Y PUESTA EN MARCHA DEL SISTEMA DE INFORMACIÓN.','PRODUCIR TEXTOS EN INGLÉS EN FORMA ESCRITA Y ORAL.','RELACIONARSE CON HABLANTES NATIVOS EN UN GRADO SUFICIENTE DE FLUIDEZ Y NATURALIDAD, DE MODO QUE LA COMUNICACIÓN SE REALICE SIN ESFUERZO POR PARTE DE LOS INTERLOCUTORES','Clave','0000-00-00','0000-00-00','Pendiente',''),(2435604,12313,'IMPLANTACIÓN','VALIDAR LOS PROCESOS DE IMPLANTACIÓN DEL SISTEMA DE INFORMACIÓN.','IMPLANTAR LA SOLUCIÓN QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÓN.','DEFINIR ESTRATEGIAS PARA LA VALIDACIÓN DE MANUALES DE USUARIO Y DEOPERACIÓN, RESPONDIENDO A LAS NECESIDADES Y SATISFACCIÓN DEL CLIENTE,FRENTE A LA SOLUCIÓN INFORMÁTICA PROPUESTA, SEGÚN POLÍTICAS DE LAORGANIZACIÓN','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435605,12313,'IMPLANTACIÓN','VALIDAR LOS PROCESOS DE IMPLANTACIÓN DEL SISTEMA DE INFORMACIÓN.','IMPLANTAR LA SOLUCIÓN QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÓN.','ELABORAR EL INFORME ADMINISTRATIVO, SIGUIENDO LOS PROTOCOLOS DE LAORGANIZACIÓN, BASADO EN LOS PLANES DE INSTALACIÓN, RESPALDO Y MIGRACIÓNDEL SISTEMA DE INFORMACIÓN, FACILITANDO LA OPERATIVIDAD Y MANTENIMIENTODE LA SOLUCIÓN INFORMÁTICA','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435606,12313,'IMPLANTACIÓN','VALIDAR LOS PROCESOS DE IMPLANTACIÓN DEL SISTEMA DE INFORMACIÓN.','IMPLANTAR LA SOLUCIÓN QUE CUMPLA CON LOS REQUISITOS PARA SU OPERACIÓN.','ELABORAR INFORMES TÉCNICOS RELACIONADOS CON LA SOLUCIÓN INFORMÁTICAIMPLANTADA, DE ACUERDO CON LAS PROPUESTAS DE ALTERNATIVAS APLICADAS,TENIENDO EN CUENTA LAS TÉCNICAS DE COMUNICACIÓN Y SEGÚN NORMAS YPROTOCOLOS ESTABLECIDOS.','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435607,12313,'EVALUACIÓN','APLICAR LAS COMPETENCIAS ADQUIRIDAS EN EL PROCESO DE FORMACIÓN EN LA ETAPA LECTIVA.','RESULTADOS DE APRENDIZAJE ETAPA PRACTICA','APLICAR EN LA RESOLUCIÓN DE PROBLEMAS REALES DEL SECTOR PRODUCTIVO, LOS CONOCIMIENTOS, HABILIDADES Y DESTREZAS PERTINENTES A LAS COMPETENCIAS DEL PROGRAMA DE FORMACIÓN ASUMIENDO ESTRATEGIAS Y METODOLOGÍAS DE AUTOGESTIÓN','Específico','0000-00-00','0000-00-00','Pendiente',''),(2435608,12313,'aaa','aaas','sada','dasdsdsa','Específico','0213-03-12','0013-03-12','En ejecución','no\r\n');

/*Table structure for table `resultado_programa` */

DROP TABLE IF EXISTS `resultado_programa`;

CREATE TABLE `resultado_programa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `resultado_id` int(11) DEFAULT NULL,
  `programa_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `programa_id` (`programa_id`),
  KEY `resultado_id` (`resultado_id`),
  CONSTRAINT `resultado_programa_ibfk_1` FOREIGN KEY (`programa_id`) REFERENCES `programa` (`id_programa`),
  CONSTRAINT `resultado_programa_ibfk_2` FOREIGN KEY (`resultado_id`) REFERENCES `resultado_aprendizaje` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `resultado_programa` */

/*Table structure for table `seguimiento` */

DROP TABLE IF EXISTS `seguimiento`;

CREATE TABLE `seguimiento` (
  `segui_id` int(11) NOT NULL AUTO_INCREMENT,
  `estado_resultado` enum('evaluado','pendiente por evaluar','finalizado') DEFAULT NULL,
  `segui_ficha` int(11) DEFAULT NULL,
  `segui_rap` int(11) DEFAULT NULL,
  PRIMARY KEY (`segui_id`),
  KEY `segui_ficha` (`segui_ficha`),
  KEY `segui_rap` (`segui_rap`),
  CONSTRAINT `seguimiento_ibfk_1` FOREIGN KEY (`segui_ficha`) REFERENCES `fichas` (`id_ficha`),
  CONSTRAINT `seguimiento_ibfk_2` FOREIGN KEY (`segui_rap`) REFERENCES `resultado_programa` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `seguimiento` */

/*Table structure for table `usuarios` */

DROP TABLE IF EXISTS `usuarios`;

CREATE TABLE `usuarios` (
  `id_usuario` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(30) DEFAULT NULL,
  `apellido` varchar(30) DEFAULT NULL,
  `usuario` varchar(30) DEFAULT NULL,
  `pw` varchar(20) DEFAULT NULL,
  `rol` enum('administrador','instructor','coordinador') DEFAULT NULL,
  `correo` varchar(50) DEFAULT NULL,
  `telefono` varchar(10) DEFAULT NULL,
  `permiso1` tinyint(1) DEFAULT NULL,
  `permiso2` tinyint(1) DEFAULT NULL,
  `permiso3` tinyint(1) DEFAULT NULL,
  `permiso4` tinyint(1) DEFAULT NULL,
  `permiso5` tinyint(1) DEFAULT NULL,
  `permiso6` tinyint(1) DEFAULT NULL,
  `permiso7` tinyint(1) DEFAULT NULL,
  `permiso8` tinyint(1) DEFAULT NULL,
  `permiso9` tinyint(1) DEFAULT NULL,
  `permiso10` tinyint(1) DEFAULT NULL,
  `permiso11` tinyint(1) DEFAULT NULL,
  `permiso12` tinyint(1) DEFAULT NULL,
  `permiso13` tinyint(1) DEFAULT NULL,
  `permiso14` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

/*Data for the table `usuarios` */

insert  into `usuarios`(`id_usuario`,`nombre`,`apellido`,`usuario`,`pw`,`rol`,`correo`,`telefono`,`permiso1`,`permiso2`,`permiso3`,`permiso4`,`permiso5`,`permiso6`,`permiso7`,`permiso8`,`permiso9`,`permiso10`,`permiso11`,`permiso12`,`permiso13`,`permiso14`) values (2,'Andres ','Amaya Paez','Andres','123','administrador','andresamayap123123@gmail.com','3125724378',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(4,'Jose Davidad','Montesino Hoyos','Josedavid123','123','instructor','josedavid@gmail.com','111111111',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(5,'Linley Catalina','Moscote','LinleyMoscote','1234','instructor','linley123@gmail.com','12321312',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(6,'Karina','Meza','KarinaMeza','123','instructor','karinameza@gmail.com','2156465465',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(7,'Carlos','Mendoza','Carlomendoza','1233','instructor','carlosmendoza@gmail.com','657894489',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(11,'Admin','Admin','Admin','123','administrador','admin@admin.com','12345689',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
